_target_: pytorch_lightning.Trainer

accelerator: "gpu"
devices: 1

fast_dev_run: False

min_epochs: 1
max_epochs: 100

#max_time: "00:01:00:00"

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
check_val_every_n_epoch: 10

gradient_clip_val: 0
gradient_clip_algorithm: "norm"

logger: False
# enable_checkpointing: False

strategy:
  _target_: pytorch_lightning.strategies.DDPStrategy
  find_unused_parameters: True
  process_group_backend: "gloo"
  timeout:
    _target_: datetime.timedelta
    hours: 120