# https://wandb.ai

wandb:
  # _target_: pytorch_lightning.loggers.wandb.WandbLogger
  _target_: pytorch_lightning.loggers.WandbLogger
  project: "spRNA-clustering"
  name: ${name}
  # save_dir: "."
  # save_dir: "${paths.output_dir}"
  save_dir: "${paths.log_dir}"
  offline: False # set True to store all logs only locally
  # offline: True # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  # id: 1syx8chb # pass correct id to resume experiment!
  # resume: "allow"
  # entity: "kexu"  # set to name of your wandb team
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
